---
title: "Chapter 5: Basic data analysis with Excel"
author: "ECON 233, Brian Krauth"
date: "Spring 2021"
output: 
  html_document:
    theme: paper
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter overview

In chapter 2, we learned how to obtain and clean a simple data set. The 
next step is to learn some tools for analyzing it. We will start with
***univariate*** statistics, i.e., statistics that describe a single 
variable.  Later in the term we will learn some ***multivariate*** 
statistics that describe the relationship between two or more variables.

In this chapter we will to:

 - Calculate and interpret the main univariate summary statistics in Excel  - 
 - Construct and interpret frequency tables in Excel
 - Construct and interpret conditional averages in Excel
 - Construct and interpret bar graphs, histograms and time series graphs in Excel

In the next chapter, we will use the tools of probability and random
variables to understand these statistics more deeply.

# Univariate statistics in Excel

Make a new working copy of [data file] and open it. 

## Summary statistics

We are going to create a nice table of summary statistics
for all of our variables, and put it in a separate worksheet.
In the course of doing so, we will learn some new tricks.

### Constructing the table

First we will create a new worksheet:

1. Click on the "+" button at the bottom of the screen to 
   create a blank new worksheet. 
  - Excel will give it some default name like "Sheet1"
2. Double click on the new worksheet tab, and enter 
   a better name for the worksheet: "Summary statistics"
   
A table of summary statistics reports various univariate statistics 
for each variable in our data set.  We will want our table to look like
this:

| Statistic | *(variable name 1)* | *(variable name 2)* | *(etc.)* |
|-----------|---------------------|---------------------|----------|
| Count     | *(count of valid observations)*
| Average   | *(average)*
| StdDev    | *(standard deviation)*
| Min
| 10th percentile
| Median
| 90th percentile
| Max

The first column specifies the statistics to be reported. Fill in 
cells A1:A9 as in the table above.

The first row specifies the variables for which we are reporting statistics. We 
could just copy-paste them from the other worksheet but let's do something 
more sophisticated and robust:

1. Go to cell B1. Type "=" but *don't hit enter*.
2. Click on the tab for Table 1, and then click on cell A1 in Table 1.
   - The formula bar now says "='Table 1'!A1"
3. Hit enter. 
   - You should now be back in cell B1 in Table 2.
   - The contents of cell B2 should be listed in the formula bar as "='Table 1'!A1" 
   - Cell B2 should display "Name" (the contents of cell A1 in Table 1!).
4. Copy the contents of cell B1 to cells C1:F1.
   
What have we done here? We have constructed a formula that successfully 
references a cell in another worksheet. Note that the relative references
are even copied over correctly. 

Now let's fill in the statistics, starting with column D (Income).

- Report the count in row 2, using the function `COUNT()`.
  - The count is the number of observations with numeric values 
    for the variable.
- Report the average in row 3, using the function AVERAGE().
  - The average is a measure of central tendency and is calculated:
    $$\bar{x} = \frac{1}{n} \sum_{i=1}^n x_i$$
- Report the standard deviation in row 4, using the function STDEV.S().
  - The standard deviation is a measure of variation and is calculated:
    $$s_x = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})^2$$
  - There is an alternative formula for the standard deviation:
    $$s_x^p = \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2$$
    This formula is used in the Excel function STDEV.P(). We will
    discuss the difference between these two statistics later.
- Report the minimum in row 5, using the function MIN().
  - The minimum is the lowest value observed in the data
- Report the 10th percentile in row 6, using the function PERCENTILE.INC().
  - The 10th percentile is a number that is above 10\% of observations
    and below the other 90\% of observations.
- Report the median in row 7, using the function MEDIAN().
  - The median is a measure of central tendency, and is a number 
    that is above half of observations and below the other half.
- Report the 90th percentile in row 8, using the function PERCENTILE.INC().
  - The 90th percentile is a number that is above 90\% of observations, 
    and below the other 10\% of observations.
- Report the maximum in row 9, using the function MAX().
  - The maximum is the highest value observed in the data

### Cleaning up the table

Our table now has all of the information we need, but it is still
kind of ugly. 

*Column widths*: The first problem is that the columns may be too narrow or too
wide. If a column is too narrow, some of its values will display
as "####". There are many different ways to adjust row heights 
and column widths, but here is the simplest:

1. Select the whole sheet by clicking in the upper left corner.
2. Select "Format" from the ribbon, and then "AutoFit Column Width".

Not only will this make everything fit, it will automatically adjust
the width as necessary when anything changes.

*Error codes*: The second problem is that the non-numeric 
variables report error codes for several statistics, and nonsense
values for some others (the minimum value of "Name" is reported
as 0). We could just exclude these variables, but it's better
to just improve the reporting. We will use the `IF()` function
for this purpose:

1. Cell B2 (count) is fine and can be left alone.
2. Cell B3 (average) gives an error code. We can make this nicer by using the 
    IF() function.  Replace `=AVERAGE('Table 1'!A2:A5)` with 
   `=IF(B2>0,AVERAGE('Table 1'!A2:A5),"")`
   - Cell B3 now displays as blank 
   - It isn't really blank, it contains a formula
     that returns the zero-length string ""
3. Copy cell B3 to cells C3:F3.
   - The numeric variables display the average, just like before.
   - The non-numeric variables now display as blank.
4. Do the same thing for the other statistics.

*Display formatting:* Finally, let's make the display formatting a little nicer.

1. Select the top row and make it **bold**.
2. Select the first column and make it *italics*.
3. Adjust the number display formats to look nice. 
   - There are many options here, so play with it 
     and see what works.  
   - Remember that the number display format has no effect 
     on the number itself.
   - By default, Excel (and most similar programs) reports
     results to more decimal places than necessary.
     There is no need to report average income to the 
     nearest cent, or average log income to the 12th 
     decimal place. Use the "Decrease Decimal"
     button aggressively to make your table more 
     readable.

## Frequency tables

### Frequency tables for discrete or categorical variables

The frequency table for a discrete or categorical variable looks like this:

| Value  | Count         | Percentage      |
|--------|---------------|-----------------|
| Male   | *(# Males)*   | *(% Males)*     |
| Female | *(# Females)* | *(% Females)*   |

where:

- the `Value` column lists all possible values of the variable 
- the `Count` column reports the number of observations in which the 
  variable matches that value
- the `Percentage` column reports the count as a percentage of the 
  total number of observations.

Let's create a frequency table for the Gender variable in our data set:

1. Create a new sheet, name it "Gender distribution"
2. Fill in row 1 and column A as in the table above.

We will fill in the `Count` column using the Excel function
`COUNTIFS()` This function takes two arguments:

- `criteria_range` gives the range of data values we should be
  looking at.  
  - In our case, this is the range of data on Gender in
    our main data sheet. 
- `criteria` is the criteria we want to match.  
  - In this case, we want to match the contents of the cell in column A.

So the formula should be `=COUNTIFS(Students!B2:B5,A2)`.  Enter that 
formula in cell B2, and the result displayed should be the number
of observations in our data that have `Gender` (the contents of the range 
`B2:B5`) equal to "Male" (the contents of cell `A2`).

Next, copy that formula into the next cell to get the count of observations 
with `Gender` equal to "Female."  Before doing so, we should change some 
of our relative references to absolute references. I'll leave it to you 
to figure out which references need to be changed. 

Next, we need to fill in the "percentage" column.  

1. To do that we just need to divide the cell in the Count column 
  (number of Male observations) by the sum of all the cells in that column
  (total number of observations).  So the formula should be `=B2/SUM(B2:B3)`
2. Change relative references to absolute references, and copy the formula 
  into cell C3.
3. By default, the percentages are displayed as numbers (e.g, 0.5).  To
  display them as percentages, highlight cell range C2:C3, select `Home`
  from the menu and click on the "%" icon in the ribbon.

We now have a frequency table.

### Frequency tables for continuous variables

Frequency tables for continuous variables are a little more complicated to 
construct.  We need to divide the data range into a set of sub-ranges or 
***bins*** and then calculate the number, proportion or percentage of 
observations falling within each bin.  

For example, we might create the following table for our income variable

| From | To | Count | Percentage |
|------|----|-------|------------|

- `Count` is the number of observations for Income that are *greater than* 
  that row's `From` value and *less than or equal to* the row's `To` value.
- `Percentage` is the count expressed as a percentage of the total count.

In constructing the bins, we need to keep in mind a few requirements and 
considerations:

- The bins need to cover the full range of the data.  In particular:
  - The lower bound of the lowest bin should be lower than the lowest 
    value in the data, and the upper bound of the highest bin should
    be higher than the highest value in the data.
  - Each bin's upper bound should be the lower bound of the next bin.
  - Ties should be addressed in a consistent manner.  
    - For example, if we have a bin for income levels from \$70,000 
    to \$80,000 and another for income levels from \$80,000 to \$90,000,
    we need a consistent rule for which bin an observation with income of 
    exactly \$80,000 should be in.
    - The usual rule is that the upper bound is inclusive, i.e., \$80,000
      goes into the \$70,000-\$80,000 bin.
- We often want the bins to be equally sized. 
  - But that isn't always the case. For example, the wealthiest person in
    Canada (David Thomson, chairman of Thomson Reuters) is estimated to 
    have a net wealth of \$39 billion, and the second wealthiest (Joseph 
    Tsai, vice-chairman of Alibaba) has \$10 billion. If wealth in Canada 
    ranges from 0 to \$39 billion and we divide the distribution into
    3 equally-sized bins, we get 1 observation in the \$26-\$39 billion
    bin,0 observations in the \$13-\$26 billion bin, and 37.6 million
    observations in the 0-\$13 billion bin. 
- We often want the upper and lower bounds of the bins to be nice round 
  numbers.
  - This is less important when we are constructing graphs.

OK, let's create our frequency table:

1. Create a new sheet, and enter the column headers in row 1, 
  and the From and To values in columns A and B.
2. To fill in the count we need to use `COUNTIFS()` with multiple
  criteria.
  - The criteria_range1 is the data range for the Income variable.
  - The criteria1 is the string ">0" or equivalently the contents
    of cell A2
  - The criteria_range2 is also the data range for the Income variable.
  - The criteria2 is the string "<=60000" or equivalently the contents
    of cell B2
  So the overall formula is 
  `=COUNTIFS(Students!C2:C5,A2,Students!C2:C5,B2)`. 
3. Fill in the remaining counts.
4. Fill in the Percentage column in the same way you did in the previous
  section, and change its display format to Percent.

> Another way to do this is by using the `FREQUENCY()` function.  However,
> this function is a tricky one to learn, and Microsoft recently 
> changed how it works.  So we will skip it.

# Graphs in Excel 

Next, we will learn to construct some simple graphs in Excel.

## A time series (line) graph

A ***time series graph*** plots one or more variables at multiple points in
time.  Conventionally, time is on the horizontal axis and the variable's
value is on the vertical axis.

In Excel, time series graphs can be implemented using either the Line
graph or the Scatter Plot graph.  Line graphs are simpler, so we will
start with that.

### Line graph basics

Open the file `1410028701-eng.xlsx`. This file contains Canadian employment statistics
for the first five months of 2020. We want to create a time series graph of 
the unemployment rate, the labour force participation rate, and the employment 
rate.  Here are the steps to create the graph:

1. Click anywhere in the table.
2. Select `Insert > Recommended Charts` from the menu.
3. The dialog box will recommend a few charts.  None of them are what we
  are looking for, so click on the `All Charts` tab at the top.
4. Now the dialog box will show a list of chart types. 
  - Click to to see what different chart types are available. We will
    not use most of them in this course, but you might find some of them 
    useful in the future.
  - Once you are done poking around, click on `Line` to see the line graph 
    options
5. The dialog box gives you several different types of line graph - line,
  stacked line, line with markers, etc. It also displays two different 
  ways of interpreting the data. Fortunately the graph we want is the default,
  so just click on `OK`.
  
We have our time series graph, but it needs some changes.

> INSERT SCREENSHOT OF GRAPH HERE.

The most important issue that we have lots of extra variables and 
need to get rid of them.  We have several ways of doing this:

- We can just click on individual lines, and hit the `Delete` key.
- We can select `Design > Select Data` and use the dialog box to exclude 
variables.

Follow either of these procedures to remove the "extra" variables.

> INSERT SCREENSHOT OF GRAPH HERE.

This looks like the graph we want, so all we need to do is tidy up the 
formatting.

### Time series graph design

There are several things I would want to change about this chart. Like other
elements of a presentation, graphs should be clear, informative, concise,
and professional in appearance.  To that end, I would want to make several 
modifications.

- To make the graph clearer and more informative:
  - Add an informative title. The title should explain what the graph is 
    about. I would go with "Canadian employment statistics 2020"
  - Add a label to the vertical axis to identify the units. I would go with "%".
  - Add visual cues to supplement the use of color. The current graph plots
    each of the time series in a different color.  This is great - color
    is a very useful way of conveying information - but it is not 
    enough.  Some in your audience might be colorblind, or they may
    be looking at a printed (black and white) copy of your chart. 
  - Consider modifying the scale of the graph. Right now, we have two 
    variables (participation and employment) that vary from 52-65
    and one variable that varies from 5-14. Plotting these very different
    variables on the same scale ends up being misleading because it
    "flattens" each time series out.  Looking at the graph, you might
    conclude that not much was changing during this time period, while
    in fact the unemployment rate more than *doubled*. 
- To make the graph more concise:
  - I would remove the grid lines, though this is a matter of taste.
- To make the graph more professional in appearance
  - Experiment with colors, legend placement and other aspects.

### Formatting our line graph

Excel charts are composed of "elements" that can be added, deleted, or 
modified. At this point, our chart has ten elements: Chart Area, Chart 
Title, Horizontal (Category) Axis, Legend, Plot Area, Vertical (Value) 
Axis, Vertical (Value) Axis Major Gridlines, Series "Unemployment Rate", 
Series "Participation Rate", and Series "Employment Rate".

Let's start with something simple: changing the plot title: 

1. Click on "Chart Title", then click anywhere inside the text box
  to start editing.
2. Enter your new title.  I went with "Canadian employment statistics, 2020"
3. Click anywhere else in the graph to stop editing.

Now, let's add a chart element: a title for the vertical axis:

1. Select `Design > Add Chart Element > Axis Titles > Primary Vertical`
  from the menu.  An axis title  appears on the graph.
2. Change the axis title "Axis title" to "%"
  
Now let's delete a chart element: the horizontal grid lines:

1. Select `Design > Add Chart Element > Gridlines > Primary Major Horizontal`

Now let's add visual cues to supplement the use of color.  Remember, we need a way
for readers who can't see color to distinguish the three time series.  There
are three basic options: 

1. Use a different *line style* (e.g., solid, dashed, dotted) for each series.
2. Add markers for each data point and use a different *marker style* for each series.
3. Add a *text label* to each series.

Let's go with markers:

1. First we need to add markers.  The easiest way to do that is by changing the 
  chart type slightly. Select `Design > Change Chart Type` from the menu.
2. Select the "Line with Markers" option from the top of the page, and click
  `OK`. 
  
You will see markers appear, but unfortunately they are all the same.  So 
we need to change the markers so they look different. For each series:

1. Click (or double-click) on the line for the series. The "Format Data Series" 
  box should appear on the right.  Click on the little paint can icon and then 
  click on "Marker" to get to the marker options.
2. Select "Built-in" and then choose a marker style from the drop-down box.
  - Some of the marker styles are not easy to tell apart, so you may need 
    to try out different marker styles until you have a good one (I chose
    circle, square and triangle).
  - You may also need to make the markers larger (I chose to increase the size
    from 5 to 8).

Our graph is now more accessible, if maybe a little less elegant.

Finally, we need to address the scale issue. We have three options:

1. Leave the graph as is.
2. Create two separate graphs, one for the employment and participation rates,
  and another for the unemployment rate.  Ideally, we would stack these two
  graphs vertically so we can make comparisons over time.
3. Add a *secondary axis*.

We will try out a secondary axis:

1. Click or double-click on the unemployment rate time series to open the 
  Format Data Series box.
2. Click on the little bar chart icon to access the series options.  You
  will see an option to "Plot Series On" either "Primary Axis" or "Secondary
  Axis". 
3. Select "secondary Axis".

The graph will now look like this:

> INSERT SCREENSHOT HERE

To explain what we are looking at:

- The primary (left) vertical axis runs from 0 to 70, and is used for the
  Participation rate and Employment rate series.
- The secondary (right) vertical axis runs from 0 to 16, and is used
  for the Unemployment rate.
  
This graph is improved in some ways - it is much clearer that unemployment changed 
a lot, for example.  But it is also more complex, and harder to interpret. One
barrier to interpretation is that it is not clear which series belongs to which 
axis. The result is that this is not *obviously* an improvement, it depends
on what we are trying to convey. 

> Knaflic's recommendation: avoid secondary axes if possible

Now that we have added a secondary axis, another issue has become clearer: the 
axis range for the participation and employment rates goes from 0 to 70, while 
the range of the data only goes from 50 to 70.  This brings us to a very
contentious issue in the presentation of data: 

- should we always include zero in our graph?
- or should we graph over the range of the data?

Again, the answer here depends on context and what we are trying to say. 

Let's suppose though, that we would like to change the primary axis from 0-70 to
50-70.  How do we do that?

1. Click on the axis to open the "Format axis" box.
2. Click on the little bar chart icon to find "Axis options"
3. Currently the axis Bounds are set to 0 (Auto) and 70.0 (Auto).  Change the
  minimum bound from 0 to 50.
  
As you can see, the graph now shows a much larger change in the participation 
and employment series since the range has been narrowed.

Is this a good thing?  Again, it depends on the context and on what information
we are trying to convey.  If we are trying to show that something big 
happened to the Canadian labour market in March and April of 2020, this graph
shows this information more clearly.

Another way of making your graphs more informative and professional is to
use color and text labels.  Let's add a text label:

1. Select `Format` from the menu and click on the text box icon.
2. Use the cursor to draw your text box right above the last point 
  on the Unemployment rate series.  Don't worry you can adjust its size 
  and location later.
3. Type "Unemployment" into the text box.
4. Resize and move the text box so that the word all fits on one line,
  and text is in an attractive position above the line.
  
Now, the label on the unemployment line is black.  But it would be nicer
if it was the same color as the unemployment line itself.

1. Select the text box if it is not already selected.
2. Select `Format > Text Fill` from the menu.  Select the color from the 
  "Theme colors" that most closely matches the line. 
  
Now do the same thing for the participation and employment series. This
is a nice improvement of the graph in two ways:

1. It makes relevant information closer and more salient - we no longer 
  have to look at the legend to figure out which series each line
  represents.
2. We no longer need the legend, and can delete it.
3. We no longer need the markers, and can delete them.

Finally, let's look at color a little more.  

- Like most other modern computer programs, Excel theoretically allows you 
  to choose from over 16 million colors.
- Real-world devices such as printers, projectors and monitors have fewer 
  colors so two theoretically different colors may end up being rendered 
  identically.
- Professional-looking graphs and documents stay within a small ***palette***
  of colors that has been carefully selected to go well together. Many large
  organizations (including SFU) have a professionally-designed brand palette 
  that is recommended for all documents from that organization.
- Both Excel and R support palettes, allow users to create custom palettes,
  and include a few built-in palettes. The current palette used our graphs
  is called "Colorful Palette 1".
  
Select `Design > Change Colors` from the menu to access other palettes.  Try
a few of them out to see which one you like best. 

## A frequency (bar/column) graph for a discrete variable

We will use a ***bar graph*** to represent the frequency distribution of a 
categorical variable.  Bar graphs use bars of different length
to represent the value of some aggregate variable in each category.

### Bar graph basics

To start constructing a bar graph:

1. Click in your fequency table for Gender.
2. Select `Insert > Recommended Charts` from the menu.
3. Click on the "All Charts" tab to see the full list of options.
4. Select either "Bar" or "Column".  Bar and column graphs are the same
  thing, but bar graphs have horizontal bars and column graphs 
  have vertical bars.

As you can see, basic bar graphs are quite simple.  There is a bar
for each category (the first column of the table) and variable
(the other columns), and the length of each bar corresponds to its 
value. 

As with our line graph, the current graph contains more information
than we actually want - it shows the count *and* the percentage, and we
really only need one of those.  Use `Design > Select Data` to get rid
of the count.  

### Bar graph design

There are several basic design considerations with bar charts. The key 
thing to understand is that the size of the bar is meant to visually
represent the value of the variable it is depicting. So the graph 
construction should reflect which comparisons we want to help 
our audience see:

- Bar graphs should almost always start at zero.  Otherwise relative sizes
  can be misleading. 
  - For example, compare the two graphs of the unemployment
    rate below. The first graph shows (accurately) that unemployment more than
    doubled from February to April. The second graph shows the same data, but
    with the origin at 4\% rather than zero. This graph is visually misleading
    because the bar depicting April unemployment is roughly ten times as 
    large as the bar depicting February unemployment.
- When using multiple categories, you can either group bars or you can stack them.

> INSERT GRAPH OF 2020 UNEMPLOYMENT WITH AXIS STARTING AT ZERO
> INSERT GRAPH OF 2020 UNEMPLOYMENT WITH AXIS STARTING AT 4%.

There are alternatives to bar graphs that I do not recommend:

- 3D bar charts.
- Pie or donut charts.

Both 3D bar charts and pie charts (and especially 3D pie charts)
are popular because they look cool.  But research on how people
process information usually find that they are *less* informative
in practice because people are much better at evaluating 
the relative size of two lines or rectangles than they are at
evaluating the relative size of two 3D boxes or pie slices. 

### Formatting our bar graph

The basics of adjusting the formatting of a bar graph are similar
to what we have already learned for line graphs.  To test your skills,
try the following:

- Modify or delete the chart title
- Change the vertical axis from decimal to percentage.

## A histogram

A ***histogram*** is just a frequency bar/column graph for 
a continuous variable.  It is constructed by sorting the variable's values 
into some number of equally-sized ***bins*** and then plotting a bar for each
bin representing counts or percentages.

### Histogram basics

Let's construct a histogram of our Income variable.

1. Select cells C1:C5.
2. Select `Insert > Recommended Charts" from the menu bar, then
  click on the "All Charts" tab to see the full set of options.
3. Select "Histogram" and click the "OK" button.

Our graph will appear.  To explain what's going on: 

- Excel has decided to form two bins, one covering the income range from 30k-75k, and 
  the other covering the range from 75k-120k.  
- There are three observations (Betty, Joe, and Sue)in the first 
  bin, and one observation (Al) in the second bin.

### Histogram design

There are two main choices in histogram design:

- How many bins and how should they be determined?
- Should we depict frequencies as counts or percentages?

By default Excel has chosen just two equally-sized bins, and is depicting
frequencies as counts. 

### Modifying our histogram

First, let's increase the number of bins.

1. Click on the horizontal axis to open "Format Axis"
2. Select the little bar graph icon, followed by "Axis options".
3. Change "Number of bins" from 2 to 4.

Second, let's make the graph look a little nicer:

- Change or delete the title
- Add an axis title (I would suggest "Income") to the horizontal axis.
- Add an axis title (I would suggest "Frequency") to the vertical axis.

