# Statistics

So far, we have learned how to model random events and random numbers, 
and we have learned how to calculate some commonly-used statistics from 
data.  This chapter ties all of that work together.

::: goals
***Chapter goals***

In this chapter we will:

- Use the theory of probability and random variables to model the statistics
  we have calculated from a data set.
- Calculate and interpret the mean and variance of a statistic from
  its sampling distribution.
- Calculate and interpret bias and mean squared error.
- Explain the law of large numbers, central limit theorem, and Slutsky's 
  theorem.
:::


## Statistics and their properties

We will use $s = s(D_n)$ as a general notation for some
statistic calculated from the data set $D_n$. We will now
define some of its properties.

::: example
We will also consider four specific examples:

- The ***sample frequency*** or ***relative sample frequency***
  of the event $x_i \in A$ is defined as the proportion of cases
  in which the event occurs:
  $$\hat{f}_A = \frac{1}{n} \sum_{i=1}^n I(x_i \in A)$$
  A closely-related statistic is the ***absolute sample frequency***
  $n\hat{f}_A$ which is the *number* of cases in which the event 
  occurs.
- The ***sample average*** of $x_i$ is defined as: 
  $$\bar{x} = \frac{1}{n} \sum_{i=1}^n x_i$$
- The ***sample variance*** of $x_i$ is defined as: 
  $$s_x^2 = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})^2$$
  A closely-related statistic is the ***sample standard deviation***
  $s_x = \sqrt{s_x^2}$ which is the square root of the sample variance.
- The ***sample median*** of $x_i$ is defined as:
  $$\hat{m}_x = m: \begin{cases} \hat{f}_{x < m} \leq 0.5 \\ \hat{f}_{x > m} \leq 0.5 \\ \end{cases}$$
:::

### The sampling distribution

Since the data itself is a collection of random variables, any statistic
calculated from that data is also a random variable, with a probability
distribution that can be derived from the DGP. 

::: example
Calculating the exact probability distribution of most statistics is 
quite difficult, but it is easy to do for the sample frequency. Let 
$p =\Pr(x_i \in A)$.
Then:
  $$n\hat{f}_A \sim Binomial(n,p)$$
In other words, we can calculate the exact probability distribution of
the sample frequency using the formula for the binomial distribution.
:::

### The mean and variance

If our statistic has a probability distribution, it (usually) has a mean
and variance as well. 

::: example
**The mean of the sample average**

Let $\mu_x = E(x_i)$ be the mean of $x_i$  Then the mean of $\bar{x}$ is:
$$E(\bar{x}) = E\left( \frac{1}{n} \sum_{i=1}^n x_i\right) = \frac{1}{n} \sum_{i=1}^n E\left( x_i\right) = \frac{1}{n} \sum_{i=1}^n \mu_x = \mu_x$$
This is an important and general result in statistics.
:::

The mean of the sample average is thus identical to the mean of the 
random variable being averaged.  The variance of the sample average
is also closely related to the variance of the random variable being
averaged.


::: example
**The variance of the sample average**

Let $\mu_x = E(x_i)$ be the mean of $x_i$ and let $\sigma_x^2 = var(x_i)$ be 
its variance. Then the variance of $\bar{x}$ is:
$$var(\bar{x}) = cov(\bar{x},\bar{x}) = E\left[\left( \frac{1}{n} \sum_{i=1}^n 
x_i-\mu\right)\left(\frac{1}{n} \sum_{i=1}^n x_i - \mu\right)\right] = \frac{1}{n^2} \sum_{i=1}^n\sum_{j=1}^n E\left((x_i-\mu)(x_j-\mu)\right) = \frac{1}{n^2} \sum_{i=1}^n\sum_{j=1}^n cov(x_i,x_j)$$
$$cov(x_i,x_j) = \begin{cases} \sigma_x^2 & i = j \\ 0 & i \neq j \\ \end{cases}$$ 
so:
$$var(\bar{x}) = \frac{1}{n^2} \sum_{i=1}^n \sigma_x^2 = \frac{n\sigma_x^2}{n^2} = \frac{\sigma_x^2}{n}$$
:::

Other commonly-used statistics also have a mean and variance.

::: example
**The mean and variance of the sample frequency**

Since the absolute sample frequency has the binomial distribution, 
we have already seen its mean and variance.  Let $p = \Pr(x_i \in A)$.
Then $n\hat{f}_A \sim Binomial(n,p)$ and:
  $$E(n\hat{f}_A) = np$$
  $$var(n\hat{f}_A) = np(1-p)$$

Applying the usual rules for expected values, the mean and variance of
the relative sample frequency is:
  $$E(\hat{f}_A) = \frac{E(n\hat{f}_A)}{n} = \frac{np}{n} = p$$ 
  $$var(\hat{f}_A) = \frac{var(n\hat{f}_A)}{n^2} = \frac{np(1-p)}{n^2} = \frac{p(1-p)}{n} $$
:::

### Parameters and estimators

A ***parameter*** is an unknown number characterizing a DGP. 

::: example
Sometimes a single parameter completely describes the DGP:

- If $x_i$ is a random sample from the $Bernoulli(p)$ distribution,
  then $p$ is a parameter.
  
Sometimes a group of parameters completely describe the DGP:

- If $x_i$ is a random sample from the $U(L,H)$ distribution,
  then $L$ and $H$ are both parameters.
  
And sometimes a parameter only partially describes the DGP

- If $x_i$ is a random sample from some unknown distribution
  with unknown mean $\mu_x = E(x_i)$, then $\mu_x$ is a parameter.
- If $x_i$ is a random sample from some unknown distribution
  with unknown median $m_x = q_{0.5}(x_i)$, then $m_x$ is a parameter.
:::

Typically there will be particular parameters whose value we wish
to know.  Such a parameter is called a ***parameter of interest***.
Our model may include other parameters, which are typically called
auxiliary parameters or nuisance parameters. 

An ***estimator*** is a statistic that is being used to ***estimate***
(guess at the value of) an unknown parameter of interest.  The distinction
between estimator and estimate is a subtle one: we use "estimate" when
talking about our statistic as a number calculated for a specific data set
and "estimator" when talking about it as a random variable.

::: example
**Commonly used estimators**

Our four example statistics are commonly used as estimators:

1. The relative sample frequency $\hat{f}_A$ is typically used as an
  estimator of the probability $p_A = \Pr(x_i \in A)$
2. The sample average $\bar{x}$ is typically used as an estimator
  of the population mean $\mu_x = E(x_i)$.
3. The sample variance $s_x^2$ is typically used as an estimator of
  the population variance $\sigma_x^2 = var(x_i)$.
4. The sample median $\hat{m}_x$ is typically used as an estimator of the
  population median $m_x = q_{0.5}(x_i)$. 

:::

Let $s$ be a statistic we are using as an estimator of some parameter 
of interest $\theta$.  We can define its ***error*** as:
  $$err = s - \theta$$
In principle, we want $s$ to be a good estimator of $\theta$, i.e.,
we want $err$ to be as close to zero as possible.  There
are several major complications to keep in mind:

1. Always remember that $err$ is not an inherent property of the
  statistic - it is a property of the relationship between the statistic
  and the parameter of interest. A given statistic may be a good
  estimator of one parameter, and a bad estimator of another parameter.
2. Since $s$ is a random variable with a probability distribution, 
  so is $err$ is also a random variable with a proability distribution. 
3. Since the value of $\theta$ is unknown, the value of $err$ is also 
  unknown.

### Bias and mean squared error

In choosing an estimator, we can consider several criteria.

The first is the ***bias*** of the estimator, which is defined as:
$$bias(s) = E(s - \theta) = E(s) - \theta$$
The bias represents the average error we would expect over multiple
trials. 

Ideally we would want $bias(s)$ to be zero, in which case
we would say that $s$ is an ***unbiased*** estimator of $\theta$.
Note that bias is always defined relative to the parameter we wish 
to estimate, and is not an inherent property of the statistic.

::: example
**Unbiased estimators of the mean**

Consider the sample average $\bar{x}$ in a random sample
as an estimator of the parameter $\mu_x = E(x_i)$. The bias is:
  $$bias(\bar{x}) = E(\bar{x}) - \mu_x = \mu_x - \mu_x = 0$$
That is, the sample average is an unbiased estimator of the population mean.

However, it is not the only unbiased estimator.  For example, suppose we 
simply take the value of $x_i$ in the first observation and throw
away the rest of the data.  This is also an unbiased estimator of $\mu_x$:
  $$bias(x_1) = E(x_1 - \mu_x) = \mu_x - \mu_x = 0$$
This example illustrates a general principle: there is rarely exactly
one unbiased estimator.  There are either none, or many.
:::

::: example
**An unbiased estimator of the variance**

The sample variance is an unbiased estimator of the population 
variance:
  $$E(s_x^2) = \sigma_x^2 = var(x_i)$$
This is not hard to prove, but I will skip it for now.
:::

If there are multiple unbiased estimators, we need to consider a 
second criterion. One option is to consider the ***variance*** of the
estimator:
  $$var(s) = E[(s-(E(s))^2]$$
Low variance is better than high variance. 

::: example
**The variance of the sample mean and an alternative estimator **

In our previous example, we found two unbiased estimators for the
mean, the sample average $\bar{x}$ and the first observation $x_1$.

The variance of the sample average is:
  $$var(\bar{x}) = \sigma^2/n$$
and the variance of the "first observation estimator: is:
  $$var(x_1) = \sigma^2$$
Since $\sigma^2/n < \sigma^2$, the sample average $\bar{x}$ has
lower variance than the first observation estimator $x_i$.

In fact, we can prove that $\bar{x}$ is the 
***minimum variance unbiased estimator*** of $\mu_x$, i.e.,
the unbiased estimator with the lowest variance.
:::

Unfortunately, once we move beyond the simple case of estimating 
the population mean, we run into several complications:

- An unbiased estimator may not exist for a particular parameter, 
  in which case there is no minimum variance unbiased 
  estimator.
- There may be a slightly biased estimator that has much lower variance
  than any unbiased estimator. In fact, we can find examples
  in which the biased estimator *always* has smaller error 
  than any unbiased estimator.

This suggests that we need a criterion that allows for a trade-off
between variance and bias.

The ***mean squared error*** of the estimator is defined as:
$$MSE(s) = E[(s-\theta)^2]$$
We can do a little math and show that:
$$MSE(s) = var(s) + [bias(s)]^2$$
The MSE criterion allows us to choose a biased estimator with low variance
over an unbiased estimator with high variance, and also allows us to choose
between biased estimators when no unbiased estimator exists.

::: example
**The MSE of the sample mean and an alternative estimator **

The mean squared error of the sample average is:
  $$MSE(\bar{x}) = var(\bar{x}) + [bias(\bar{x})]^2 = \frac{\sigma_x^2}{n} + 0^2 = \frac{\sigma_x^2}{n}$$
and the mean squared error of the first observation estimator is:
  $$MSE(x_1) = \sigma_x^2$$
The sample average is the preferred estimator by the MSE criterion,
so in this case we get the same result as applying the MVUE criterion.
:::

The sample median is an example of a biased estimator for the population
median. 

::: example
**The sample median is a biased estimator**

Consider a simple example in which $x_i \sim Bernoulli(0.6)$ and $n = 1$.
Then the population median is the most likely value for $x_i$:
  $$m_x = 1$$
and the sample median is the observed value for $x_i$:
  $$\hat{m}_x = x_1$$
The mean of $\hat{m}_x$ is:
  $$E(\hat{m}_x) = E(x_1) = p$$
and so the bias is 
  $$E(\hat{m}_x - m_x) = p - 1$$
Now this is a very simple example, but the basic idea applies more generally:
there is usually[^2] no unbiased estimator for the population median
or any other population quantile. 
:::

[^2]: There are exceptions. For example, if the population median and 
  the population mean are identical, then the sample average is an 
  unbiased estimator of both.


::: example
**A biased estimator with lower MSE than the sample average**

Here's an example of a biased estimator that has lower MSE than any unbiased
estimator.  Suppose that we know that $x_i \sim N(\mu_x,\sigma_x^2)$ and
that $\mu_x \geq 0$.  

The sample average $\bar{x}$ is a good estimator for $\mu_x$, 
but since we know $\mu_x \geq 0$ we can do better. 
Let 
  $$s = max(\bar{x},0)$$
Intuitively, this will be a better estimator since it is identical 
to $\bar{x}$ whenever $\bar{x} \geq 0$ and strictly closer to $\mu_x$ 
whenever $\bar{x} < 0$. 

With a little bit of math we can show that this alternative estimator 
is biased:
$$E(s) > E(\bar{x}) = \mu_x$$
but has lower MSE than the (unbiased) sample average:
$$MSE(s) < MSE(\bar{x})$$
:::

### Standard errors

Parameter estimates are typically reported along with their
***standard errors***.  The standard error of a statistic is
an estimate of its standard deviation.

::: example
**The standard error of the average**

We have shown that the sample average provides a good estimate
of the population mean, and that its variance is:
  $$var(\bar{x}) = \frac{\sigma_x^2}{n} = \frac{var(x_i)}{n}$$
Since $s_x^2$ is an unbiased estimator of $var(x_i)$ we can use
it to construct an unbiased estimator of $var(\bar{x})$:
  $$E\left(\frac{s_x^2}{n}\right) = \frac{E(s_x^2)}{n} = \frac{var(x_i)}{n} = var(\bar{x})$$


We might also want to estimate the standard deviation of $\bar{x}$. A natural
approach would be to take the square root of the estimator above, yielding:
  $$se(\bar{x}) = \frac{s_x}{\sqrt{n}}$$
This is the conventional formula for the standard error of the sample
average, and is typically reported next to the sample average.
:::

In general, the standard error of a statistic is an estimator of the statistic's
standard deviation. It is not exactly unbiased, but its bias is typically small and it has some other useful properties that we will use later.

## Asymptotics

So far, we have described statistics and estimators in terms
of their probability distribution and the mean, variance
and mean squared error associated with that probability 
distribution. 

We are able to do this fairly easy with both sample averages 
and sample frequencies (which are also sample averages)
because they are sums. Unfortunately, this is not so easy 
with other statistics (e.g. standard errors, medians, 
percentiles, etc.) that are nonlinear functions of the data.

In order to deal with those statistics, we need to construct
approximations based on the ***asymptotic*** properties
of the statistics.  Asymptotic properties are properties 
that hold approximately, with the approximation getting 
closer and closer to the truth as the sample size gets 
larger.  

Properties that hold exactly for any sample size 
are sometimes called ***exact*** or ***finite sample***
properties. All of the results we have discussed
so far are finite sample results.

We will state three main asymptotic results, the law of large
numbers, the central limit theorem, and Slutsky's theorem. All
three rely on relatively sophisticated math, so I will not
expect you to do much with them.  Please focus on the intuition
and interpretation and don't worry too much about the math.

### The law of large numbers

The ***law of large numbers*** (LLN) says that for a large enough random
sample, the sample average is almost identical to the corresponding
population mean.  

In order to state the LLN, we need to introduce some concepts. Consider
a data set $D_n$ of size $n$, and let $w_n$ be some statistic
calculated from $D_n$. We say that $w_n$ ***converges in probability*** 
to some constant $c$ if:
  $$\lim_{n \rightarrow \infty} \Pr( |w_n - c| < \epsilon) = 1$$
for any positive number $\epsilon > 0$.

Intiutively, what this means is that for a sufficiently large $n$ 
(the $\lim_{n \rightarrow \infty}$ part), $w_n$ is almost certainly
(the $\Pr(\cdot) = 1$ part) very close to $c$
(the $|w_n-c| < \epsilon$ part).

We have a compact way of writing convergence in probability:
  $$w_n \rightarrow^p c$$
means that $w_n$ converges in probability to $c$. 

Having defined our terms we can now state the law of large numbers.

::: fyi
**LAW OF LARGE NUMBERS**: Let $\bar{x}_n$ be the sample average 
from a random sample of size $n$ on the random variable $x_i$ with
mean $E(x_i) = \mu_x$. Then
  $$\bar{x}_n \rightarrow^p \mu_x$$
:::

::: example
**The LLN in the economy**

The law of large numbers is extremely powerful and important, as it
is the basis for the gambling industry, the insurance industry,
and much of the banking industry. 

A casino works by taking in a *large* number of *independent* small
bets. As we have seen for the case of roulette, these bets
have a small house advantage, so their average benefit to 
the casino is positive. The casino can lose any bet, but the 
LLN virtually guarantees that the gains will outweigh the 
losses as long as the casino takes in a large enough number
of independent bets.

An insurance company works almost the same as a casino. Each of
us faces a small risk of a catastrophic cost: a house that
burns down, a car accident leading to serious injury, etc.
Insurance companies collect a little bit of money from each
of us, and pay out a lot of money to the small number of 
people who have claims. Although the context is quite different,
the underlying economics are identical to those of a casino:
the insurance company prices its products so that its revenues 
exceed its expected payout, and takes on a large number of
independent risks.

Sometimes insurance companies do lose money, and even go 
bankrupt. The usual cause of this is a big systemic 
event like a natural disaster, pandemic or financial crisis
that affects everyone.  Here the independence needed for the LLN
does not apply.
:::


### The central limit theorem

The ***Central Limit Theorem (CLT)*** is an even more powerful result.
It roughly says that for a sufficiently large sample size we can
approximate the entire probability distribution of 
$\bar{x}$ by a normal distribution.

As with the LLN, we need to invest in some terminology before we can
state the CLT.  Let $w_n$ be a statistic calculated from $D_n$ and 
let $F_n(\cdot)$ be its CDF. We say that $w_n$ 
***converges in distribution*** to a random variable $w$ with CDF $F(\cdot)$, or 
  $$w_n \rightarrow^D w$$
if
  $$\lim_{n \rightarrow \infty} |F_n(a) - F(a)| = 0$$
for every $a \in \mathbb{R}$.

Convergence in distribution means we can approximate the actual CDF
$F_n(\cdot)$ of $w_n$ with its limit $F(\cdot)$.  As with most approximations,
this is useful whenever $F_n(\cdot)$ is difficult to calculate and $F(\cdot)$
is easy to calculate. 

::: fyi
**CENTRAL LIMIT THEOREM**: Let $\bar{x}_n$ be the sample average 
from a random sample of size $n$ on the random variable $x_i$ with
mean $E(x_i) = \mu_x$ and variance $var(x_i) = \sigma_x^2$. Then
  $$z_n \rightarrow^D z \sim N(0,1)$$
:::

What does the central limit theorem mean?

  - Fundamentally, it means that if $n$ is big enough then the probability
    distribution of $\bar{x}_n$ is approximately normal 
    *no matter what the original distribution of $x_i$ looks like.*
  - In order for the CLT to apply, we need to rescale $\bar{x}_n$
    so that it has zero mean (by subtracting $E(\bar{x}_n) = \mu_x$) 
    and constant variance as $n$ increases (by dividing by 
    $sd(\bar{x}_n) = \sigma_x/\sqrt{n}$)).  That rescaled sample
    average is $z_n$.  
  - In practice, we don't usually know $\mu_x$ or $\sigma_x$ so 
    we can't calculate $z_n$ from data. Fortunately, there are some
    tricks for getting around this problem that we will talk
    about later.

### Consistent estimation

The law of large numbers and central limit theorem apply to the sample
mean, but we are interested in other estimators as well.

In general, we say that the statistic $s$ is a ***consistent*** 
estimator of a parameter $\theta$ if:
$$s \rightarrow^P \theta$$
It will turn out that most of the statistics we use are consistent 
estimators of the thing we typically use them to estimate. 

The key to this property is a result called ***Slutsky's theorem***.
Slutsky's theorem roughly says that if the law of large numbers
and central limit theorem applies to a statistic $s_n$, it also
applies to $g(s_n)$ for any continuous function $g(\cdot)$.

::: fyi
**SLUTSKY THEOREM**: Let $g(\cdot)$ be a continuous function. Then:
  $$w_n \rightarrow^p c \implies g(w_n) \rightarrow^p g(c)$$
and:
  $$w_n \rightarrow^D w \implies g(w_n) \rightarrow^D g(w)$$
:::

What is the importance of Slutsky's theorem?  Most commonly used statistics
can be written as continuous functions of a sample average (or several 
sample averages). Slutsky's theorem

  - extends the LLN to these statistics 
    - Most commonly used statistics are consistent estimators of 
      the corresponding population parameter.
  - extends the CLT to these statistics
    - Most commonly used statistics are also asymptotically normal.

The math needed to make full use of Slutsky's theorem is beyond the scope
of this course, so all I am asking here is for you to know that it can be
used for this purpose.
