# Advanced data cleaning with Excel

In this chapter we will learn how to:

- Find economic data from key sources.
- Move data files across multiple file formats and platforms.
- Link and merge data across multiple files
- Construct lookup tables using HLOOKUP and VLOOKUP
- Work with Excel tables

## Advanced data cleaning in Excel

### Errors in formulas

Go to any blank cell and enter the formula `=ln(B2)`. You will see
that the cell displays the text `#VALUE!`.  This is an example of
an error code - cell B2 contains the string "Male", so you are asking 
Excel to calculate ln("Male"). Excel's most commonly-used error 
codes are:

- `#VALUE!` means you have given a function the wrong type of argument
  (for example, giving the `ln()` function a string rather than the number.
- `#NAME?` means you have referenced a function that does not
  exist.
- `DIV/0!` means you have divided by zero.  For example, this appears
  when you take the average of a set of empty or non-numeric cells.
- `#REF!` means you have referenced a cell that does not exist.  This
  usually happens when you delete rows or columns.
- `#NUM!` means that the result of your numeric calculation is not a 
  number.  For example, if you take the square root of a negative number.
- `#NA` means that a lookup function (vlookup or hlookup) was unable to
  find a match.  I'll explain what that means later on when we talk 
  about vlookup.

An error code is sometimes helpful in figuring out what has gone wrong.

### CSV files

Normally, Excel works with files in its native format, `.xlsx` files.

However, Excel is not the only program that works with data,
and so we will often find data in other formats. We will also sometimes
want to save our data in a format that can be read by other programs,
for example R.

The most common and useful general-purpose format for tabular data
is called the "comma separated values" or ***CSV*** file format.

#### What is a CSV file?

A CSV file is just a text file with the following features:

- Each line in the file represents a row in the table
- Within each row, cell values are separated or ***delimited*** by commas.
- Where necessary, text values are enclosed in quotes.

For example, this CSV file:
```
Name,Year of birth,Year of death
"Mary, Queen of Scots",1542,1547
Mary I,1516,1558
Elizabeth I,1533,1603
```
will appear in Excel as the table:

CSV files have several important limitations relative to Excel 
files:

1. A CSV file can only contain one table, while an Excel file
   can contain multiple tables.
2. A CSV file can only contain cell values, and cannot contain:
   - Formulas
   - Formatting
   - Graphs
   - Any other fancy Excel features
   
These limitations are also the main advantage of the CSV file: they are simple
ways of reporting tabular data and can be read by virtually any program.

#### Exporting CSV files from Excel

Let's save our Excel worksheet as a CSV file.

1. Open [filename] in Excel, and go to [sheet]
2. Click on `File >  Save As`. You will see:
   - a text box giving the name of the file (currently [filename]) 
   - a drop-down box giving the file format (currently 
     `Excel Workbook (*.xlsx)`).
3. Select `CSV (Comma delimited) (*.csv)` from the drop-down
   box and enter a filename in the text box.
4. Click on the `Save` button.
   - You will get a warning message: "The selected file type does
     not support workbooks that contain multiple sheets. To save only
     the active sheet click OK...."
5. Click on the `OK` button.
6. Close Excel.
   - You will get another warning message: "Want to save your changes
     to [filename].csv?"  Click `Don't save`.
     
You have created a CSV file.

#### Importing CSV files into Excel

Let's take a look at our CSV file. You can open it in Excel by just 
double-clicking on it. You may notice that it is somewhat different from the 
Excel file:

- The cells are unformatted, no boldface, no special number formats, etc.
- The columns are all the same width; in some cases this might mean that a 
  cell's value appears as "#####". You can fix this by changing the
  width of the column.
- All of the other worksheets and all of the graphics are gone.

This is of course, what the CSV file is supposed to do.  You can now 
add formatting, formulas, and any other Excel feature to the table.
Just remember to save it as an Excel file and not a CSV file so that
these features are saved too.

#### Other file formats

In addition to CSV files, we will run into other file formats.
These include:

- Text files in which cells are delimited by spaces or tab characters.
  ```
  Name "Year of birth" "Year of death"
  "Mary, Queen of Scots" 1542 1547
  "Mary I" 1516 1558
  "Elizabeth I" 1533 1603
  ```
- Text files in which cells are of a fixed width:
  ```
  Name                   Year of birth   Year of death
  Mary, Queen of Scots   1542            1547
  Mary I                 1516            1558
  Elizabeth I            1533            1603
  ```

You can open these files in Excel too.

Excel also has a wide variety of tools for obtaining data from various
databases, online services, etc. We do not have time to explore all of these
tools, but you can click `Data` on the menu bar and look around to see
what is available.

#### Text to columns

Sometimes you will run into an Excel sheet that looks like this:

[Insert picture here]

This will happen if a text file has been incorrectly imported,
or if you have copied-and-pasted data from a PDF file or web 
page.  Fortunately, Excel has a way of fixing that:

1. Select the column with the data.
2. Select `Data` from the menu, then `Text to Columns`.
3. The "Text to Columns Wizard" will appear; answer its questions
   and you will be good to go.

### Linking data and lookup tables

Column J in our data set provides the student's state of residence
using the state's two-letter postal abbreviation. Suppose we want 
to create another variable giving the state's full name. We can
do this by constructing a ***lookup table*** and using the 
`vlookup()` function. 

Our lookup table already exists, in the worksheet called `States`. It
has several features:

- The first column has the state identifier (postal abbreviation).
  - The vlookup command requires that the identifier be in the first
    column.
- The remaining columns have information about the states.  
  - The one we want is the `StateName` variable in column 2.

Let's add our state list:

1. Enter "StateName" in cell K1.
2. Enter `=VLOOKUP(J2,States!$A$1:$B$3,2)` in cell K2.
3. Copy/paste or fill this into the rest of column K.

The vlookup function takes three arguments:

1. The cell containing the identifier for the current observation. 
  - In our example, this is cell   
2. The full cell range of the the lookup table.
  - In our example this is the full table of state data in cells
    `States!A$1:B$3`. 
  - Notice that I use absolute references here so the fill works.
3. The column in the lookup table we want to retrieve values from.
  - In our example, this is the StateName column in the lookup table,
    which is located in column 2.
 
A few things to notice about this:

- In order for vlookup to work, we need the first column in the 
  lookup table to be the identifier.  This should be the case
  if you are following good data practices.
- If vlookup does not find a match, it returns `#N/A`.
- vlookup is short for "vertical lookup" because it assumes that 
  your data has variables in columns and observations in rows.  
- There is also a function called hlookup that works with variables in rows and observations
  in columns.

### Aggregating by group

Suppose you want to create a new variable that gives the average income
among students in the same state.  This is an example of aggregation by 
group.

1. Enter "AvgStateInc" in cell L1.
2. Enter "=AVERAGEIF(J$2:J$5,J2,C$2:C$5)" in cell L2.
  - The first argument `J$2:J$5` gives the range of state values to look up.
  - The second argument `J2` gives the state value of the current row.
  - The third argument gives the range of income values to average over.
3. Copy/paste or fill into the remaining cells in column L.

You can see that this formula takes on one value for the Michigan students,
and another value for the Texas students.

### Excel Tables

#### Creating a table

To create an Excel table, go to any cell in your table, and
select `Home` and then `Format as Table` from the menu. A set of
visual styles will drop down.  Select whichever one looks nice to
you.

A dialog box will come up that looks like this:

> Insert Format As Table dialog box here.

Excel will try to guess the range of your table, and whether your
table has headers (it should).  Correct Excel's guesses if necessary, and press OK. You have a table!

#### Some things you can do with tables

There are several things you can do with tables.  Most of them
are on the ribbon associated with the `Design` menu option. Note
that the `Design` menu is context-dependent - it only appears if
the currently-selected cell is in a table.

Here are a few things you can do:

- Change the name of your table:
  - By default your table will be named Table1 (or Table2, Table3,
    etc.).  
  - You can change its name in the upper right corner of the `Design`
    ribbon. 
  - You can refer to the table by name in formulas.
- Convert it back to a normal range 
  - Select  `Convert to Range` from the `Design` ribbon.
- Sort and filter
  - Click on the drop-down boxes in the header row.

Another nice feature of Excel tables is that it automatically uses
variable names rather than cell addresses in formulas. To see
how this works, click in cell H3 and look at the formula box.  The formula used to say `= D3 - C3` but now it says `=[@Income]-[@Spending]`. This
feature makes it much easier to tell the content of a formula and to
avoid making mistakes.

#### Adding observations, variables and totals  

You can add observations (rows) to the bottom of a table, and Excel will
automatically fill in any formulas.

1. Make sure that the `Total row` check box is unchecked.
2. Enter "Fred" in cell A6.

As you can see, Excel has added row 6 to the table, and filled in
all calculated cells automatically.

You can also add variables (columns) to the end of the table.

1. Go to cell J1 and enter `LogSavings`. 
  - As you can see, Excel automatically extends the table to include 
    this variable.
2. Go to cell J2 and enter `=ln(H2)` or `=LN([@Savings])`. 
  - As you can see, Excel automatically fills in the formula 
    for all other rows.

Finally, you can add a summary row (Excel calls it a "total row"):

1. Click on the `Total Row` check box in the `Design` ribbon.
  - By default, Excel will only show a total for the last column.
2. Go to cell C6. You will notice a drop-down box appears in the
  cell. Select "Average" from the drop-down box
  - The average value for this variable now displays in the cell
  - You can show the sum, count, standard deviation, etc. instead 
    of the average.
    
https://support.office.com/en-us/article/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c. 

#### Using Slicers

To be added.

### Data validation

To be added.

### Power Query

To be added.






## Data and project management

### Some basic principles

#### Reproducible analysis 

The goal of most data analysis is to get some interesting results that we can
report to our audience.  Sometimes our audience is decision-makers in business
or government, sometimes it is the public, and sometimes it is other
researchers.  For our audience it is important for the results of our
analysis to be:

- **Clear**: the audience can understand the information you are conveying.
- **Informative**: the information is new and useful.
- **Concise**: the relevant information is not obscured by irrelevant 
   information.
- **Professional**:  the presentation of our results is visually attractive
   and follows the professional conventions of your field.

At the same time, the underlying analysis needs to be:

- **Accurate**: errors are minimized, and no "shortcuts" (e.g. fraudulent
   data) are taken
- **Transparent**: another analyst can determine how each result was obtained.
   - this other analyst may be you in 6 months!
- **Reproducible**: another analyst can derive, explore, and extend the results.

The key to accuracy, transparency and reproducibility is to carefully 
maintain a record of all data and analysis steps leading to every result 
that is ever reported. This record can then be shared with others.      

#### Workflow and version control

Think about the last time you wrote a paper for school.  Did you just sit down
and write from the beginning to the end, and then turn in the result?
Probably not.  There was probably exploration, learning, and 
trial-and-error. You probabaly threw away entire paragraphs, had little scraps 
of writing, and went through several revisions. Data analysis follows a similar
process.  Most of what you do will not end up in the final version, 
and it would be a huge burden to have to maintain a record of everything
you do. So what should we do?

The standard solution to this problem is to plan your ***workflow*** in advance.
Your workflow is a system of rules and procedures you follow to organize your work,
and needs to include some kind of ***version control*** system.  A 
version control system maintains multiple versions of your files in a way that
makes it easy to experiment without having to repeat steps.

Serious programmers and data analysts often work in large teams 
on massive projects that may take many years. The person who originally 
wrote a particular piece of the code may have left the 
company decades ago, and the system as a whole may be so complex that no one
individual understands every detail.  These teams need to be constantly adding 
new capabilities and fixing errors (bugs) without accidentally introducing new 
errors or getting in one another's way. 

To deal with these issues, serious programmers and data analysts use 
specialized software to implement version control. The most commonly 
used version control system combines two tools called Git and GitHub.
We will not use these tools in this course, but I'd like to describe
them so you have an idea what a robust version control system looks 
like:

- Git is a computer program that maintains a distributed 
  database of file versions for a single project.
  - Every time you edit a file, the changes are logged in the database.
  - Past changes can be viewed and can easily be undone.
  - There is always a "master" version of each project file.  It is usually
    under the exclusive control of a single user.
  - Any user can create a local copy called a "branch", and can edit the 
    files in their branch without affecting the master version.
  - The user who controls the master version can "pull" 
    changes in from any branch to the master. Usually this is done after the 
    branch owner issues a "pull request."
- GitHub is an online user interface to Git that provides various other features
  like access control, task lists, and bug tracking.

Both Git and GitHub are free for most users, but we will not use them
in this course. You are working alone, and your projects are simple.

Instead we will follow some of the basic principles of version control
without using any fancy software.

### Setting up your project

Our simple verison control system will be a set of four rules.

1. Organize work into projects and keep all project-related files together.
2. Keep all original ("raw") data separate and document its sources.
3. Avoid changing data; use existing data to make new data instead.
4. Maintain a master version, but keep selected intermediate versions as well.

We will now set up our first project according to these rules.

#### Make a project folder

**RULE #1: Organize work into projects, and keep all project-related files together.** 

For this class, it is natural to think of each chapter or assignment as a
separate project.

1. Decide where on your computer you want to keep your work for this course. 
   - I will refer to that location as `[mywork]`.
2. Create a folder called `[mywork]\Chapter3`
3. Create the following subfolders:
   -  `[mywork]\Chapter3\raw`
   -  `[mywork]\Chapter3\doc`

#### Get external data

**RULE #2: Keep all original ("raw") data separate and document its sources.** 

1. Download the file [LINK HERE] and put it in your `raw` folder.
2. Create a text file in your ```raw``` folder called `README.txt`
   and type the line:
   `[filename] dowloaded [today's date] from [link]`
   and save. 
   
Every time you add a file to the `raw` folder, you should add the
corresponding line of information to `README.txt`.

#### Make working copies

**RULE #3: Avoid changing data; use existing data to make new data instead.** 

The `raw` directory is intended to contain the unaltered, original data
files as you received them.  Aside from the `README.txt` file, you should
*never* alter the data files in the `raw` directory. Why not?

- Editing the raw data kills reproducibility, because the changes you have
  made are not documented.
- It is very easy to make a mistake when editing data directly, and these
  mistakes are undetectible if you don't have the original data.

But the whole point of analysis is that we want to do something to the data,
so what do we do? This is an easy problem to solve in R, because R keeps the
data and analysis in separate files. In Excel the problem is more difficult
because Excel keeps the data and analysis in the same file. We will solve the
problem by making a  ***working copy*** of the original data, and editing the
working copy.

1. Copy [filename] from the `raw` subfolder to your main project folder.
   - This is your working copy.
2. Rename the working copy.
   - You should choose a brief but clear name. Avoid names like "my file.xlsx."
   - I usually put the current date in YYMMDD format at the end of my filenames, 
      for example "NLSY wage data 200614.xlsx" This makes it easier to keep earlier 
      versions of a file while still knowing how they are related and which 
      version is the current one.
3. Open the working copy. 

#### Maintain a master version

**RULE #4: Maintain a master version, but keep selected intermediate versions too.** 

Think about the last time you wrote a paper for school. Did you just start at the
beginning, write until you reached the end, and turn in the result?  Probably not.
You may have written an outline, then filled in different sections in a random order.
You may have decided you didn't like a paragraph, deleted it, and then decided to 
put it back.  After several rounds of this, you eventually settled on the version
you turned in.

Here's what I recommend:

1. Number versions of files sequentially (e.g. "Wage analysis 1", Wage analysis 2", etc.)
   or by date (e.g. "Wage analysis 200614"m "Wage analysis 200706", etc.)
2. The file you are currently working on is your working copy. Feel free
   to do whatever you want with the working copy.  All other copies should be read-only.
3. At regular intervals you should:
   a. Make your working copy the master copy.
   b. Make a copy of this new master copy and call that your new working copy.

When should you make the working copy the master copy? It depends on the nature of the work.
Most people would do this upon completion of a significant step in the project.
Others might do it at the end of each working day. Ideally, these two will often
coincide. It all depends on what works best for you.

