# Advanced topics in statistics

## Chapter 10 overview

In this chapter we will learn how to:

- Describe the relationship between two random variables
  using joint and conditional probabilities.
- Describe the relationship between two random variables
  using the covariance and/or correlation coefficient.
- Describe the relationship between two random variables
  using the conditional expectation function (CEF).
- Use the CEF to construct predictions.
- Calculate conditional frequencies, covariances and 
  correlations from a table of data.
- Distinguish between methods of estimating a CEF 
  (conditional averages, linear regression, and smoothing)
  and interpret an estimated CEF.

## Multivariate statistical methods

### Joint and conditional frequencies

See conditional averages below.

### Estimating covariance and correlation

The sample covariance of $x_i$ and $y_i$ is:
  $$s_{x,y} = \frac{1}{n-1} \sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})$$
and their sample correlation is:
  $$\rho_{x,y} = \frac{s_{x,y}}{s_x s_y}$$
where $s_{x,y}$ is the sample covariance, $s_{x}$ is the sample
standard deviation of $x_i$ and $s_{y}$ is the sample 
standard deviation of $y_i$.

For example, suppose that we have the following data:

> INSERT TABLE HERE: 2 columns (x and y), 3 rows of data

Then we can calculate:
  $$\bar{x} = \frac{1}{n-1}\sum_{i=1} x_i = ?$$
  $$\bar{y} = \frac{1}{n-1}\sum_{i=1} y_i = ?$$
  $$s_{x} = \frac{1}{n-1}\sum_{i=1} (x_i - \bar{x})^2 = ?$$
  $$s_{y} = \frac{1}{n-1}\sum_{i=1} (y_i - \bar{y})^2 = ?$$
  $$s_{xy} = \frac{1}{n-1}\sum_{i=1} (x_i - \bar{x})(y_i - \bar{y}) = ?$$
  $$s_{xy} = \frac{s_{xy}}{s_{x}s_{y}} = \frac{?}{? + ?} = ?$$

> The sample covariance and correlation can be calculated in Excel
> using the `COVARIANCE.S()` and `CORREL()` functions.

The sample covariance and correlation have several properties:

- The sample covariance is a consistent and unbiased estimator of the 
  (population) covariance.
- The sample correlation is a consistent (but not unbiased) estimator
  of the (population) correlation.
- As with the population correlation, the sample correlation ranges 
  from -1 to 1.

### Estimating conditional expectations

#### Conditional averages

When our conditioning variable $x_i$ only takes on a 
few values, the CEF can be estimated by constructing ***conditional averages***:

1. Dividing up the sample into $k$ subsamples, one for each possible value of $x_i$
2. Averaging $y_i$ within each subsample.

For example, suppose we want to estimate the CEF of earnings given (binary)
gender using the following table of data from a random sample of Canadians:

> INSERT TABLE OF DATA HERE

We  can use the average earnings of women in our sample to estimate the mean
earnings of women in the population, and the average earnings of men in 
our sample to estimate the mean earnings of men in the population.

> The conditional average can be calculated in Excel
> using the `AVERAGEIF()` function.

The conditional average is just an average, so all of the results we have
learned for averages apply: 

- It is an unbiased and consistent estimator of the corresponding 
  conditional mean.
- It is asymptotically normal, and we can use the same formulas for standard
  errors, hypothesis tests, and confidence intervals as we use for regular
  averages/means.

When $x_i$ is continuous, or takes on many values, we run into some problems
with the conditional average:

- The subsamples become very small, and so the averages become very noisy.  
- The results are often hard to intepret.

So we will also need some other techniques.

#### Linear regression

One solution is to assume that the CEF is a straight line, or can be
well-approximated by a straight line.  In that case we can estimate
the CEF by a technique called ***linear regression***.  Linear
regression calculates the straight line that fits the data best.

> EXAMPLE PLOT HERE: scatter plot with (good) linear fit

You will learn much more about linear regression in ECON 333.

#### Binning and smoothing

Figure ??? below shows an example in which $x_i$ takes on many values 
(so conditional averages won't work) and the relationship betwee
$x_i$ and $y_i$ is clearly not linear (so linear regression will be misleading).
What do we do there?

> EXAMPLE PLOT HERE: scatter plot with bad linear fit

One solution is to divide the range for $x_i$ into a set of ***bins** and then
take averages within each bin. We can then plot the average $y_i$ within each
bin against the midpoint of the bin. Figure ??? below shows the result of 
binning our data.

> EXAMPLE PLOT HERE: scatter plot with binned fit

Another solution is to ***smooth***.  There are many different techiques for 
smoothing, but they are all based on taking a weighted average of $y_i$ near 
each point, with high weights on observations with $x_i$ close to 
that point and low (or zero) weights on observations with $x_i$ far 
from that point.  Figure ??? below shows the result of smoothing our data.

> EXAMPLE PLOT HERE: scatter plot with smoothed fit

Both binning and smoothing require the analyst to choose how smooth she wants
the estimated CEF to be:

  - In binning, this is determined by the number of bins. 
    - The first graph in Figure ??? shows fewer bins
    - The second graph in Figure ??? shows more bins
  - In smoothing, this is determined by some smoothing parameter.
    - The first graph in Figure ??? shows a smoother relationship
    - The second graph in Figure ??? shows a lsss smooth relationship

Computer programs that do binning or smoothing usually have some default
way of setting these parameters so the results look reasonable.

> EXAMPLE PLOT HERE: binned fit, fewer bins and more bins
> EXAMPLE PLOT HERE: scatter plot with smoothed fit, oversmoothed and undersmoothed

## Applications of statistics

### Description

The simplest application of statistics is the one we have emphasized so
far: using statistics calculated from a random sample as estimates
of the corresponding value in the population from which it was drawn.

For example, Statistics Canada's estimate of the unemployment rate uses the 
unemployment rate among the approximately 100,000 respondents to the 
Labour Force Survey to estimate the unemployment rate among the much 
larger population of approximately 30 million working-age Canadians.
  
### Prediction

Another important application of statistics is to form ***predictions***.
For example, we might use data to learn the historical relationship 
between the unemployment rate and the previous month's unemployment
rate, and then might use that relationship to predict next month's 
unemployment rate.

In our framework, this amounts to estimating the conditional expectation
function $E(y_i|x_i=a)$, and then constructing forecasts for $y_i$
by plugging in a value for $x_i$.

This is a reasonable thing to do, but there are some common issues:

- In order to work, the relationship between $y_i$ and $x_i$ must be
  ***stable***, that is, the sample used to estimate the CEF is reasonably
  representative of the population in which we will be forecasting.
- In order to estimate $E(y_i|x_i=a)$ for a particular value of $a$
  that value must be in the support of our sample (we must have observed
  cases in which $x_i=a$) or we must have a model (e.g. a linear model)
  that allows extrapolation.

### Causal inference (TO BE ADDED)


