---
title: "Chapter 6: Simulation with Excel"
author: "ECON 233, Brian Krauth"
date: "Spring 2021"
output: 
  html_document:
    theme: paper
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter overview

In this chapter we will:

 - Follow good data management practices 
 - Use formulas in Excel
 - Gather resources and tools, including all needed computer software.

# Preliminaries

1. Start Excel.
2. Open a blank new workbook.

# Simulation

One of the most useful ways to understand a random process is to ***simulate*** it.
Simulation means we generate random numbers, plug them into our model of the 
data generating process to generate fake data, and then analyze the fake data 
as if it were real. We can do this repeatedly to get a sense of how well
our analysis is likely to work.

## Generating a uniform random number

We will start by generating a single random number:

1. Go to cell A2 in your blank worksheet, and enter "=RAND()". 
2. Copy cell A2 into cells A3:A101.

The RAND() function generates a random number between zero and one, with each
possible number in that range having equal probability.  This
particular probability distribution is called the *standard uniform* 
distribution, and is particularly important for simulation.

Let's do something simple with these random numbers.

1. Go to cell A103 and enter "=AVERAGE(A2:A101)"

Cell A13 now contains the average of our 100 random numbers. It 
will usually be somewhere around 0.5.

You may notice that the random numbers all changed after you 
entered the formula in cell A103. 

- This is because every time you change the contents of a cell 
  in your spreadsheet,
  Excel automatically recalculates all formulas. This includes
  forumlas that return random numbers, so you get new random
  numbers any time you make a change.
- You can force Excel to recalculate at any time by pressing
  the F9 key (in Windows, not sure what to do in macOS).
- You can turn off automatic recalculation, but I don't 
  recommmend it.

Where do these random numbers come from?

- First of all, they are not actually random but ***pseudo-random***. 
  That is, they follow a predetermined
  sequence so if you know the current number and the rule for calculating 
  the next number, you know the next number.
- The calculation rule is complicated enough that the resulting sequence
  of numbers is nearly indistinguishable from truly random numbers.
- The only thing that might be kind of random is the starting point.
  Many random number generators choose a starting point based on some
  "real world" event like the last time the computer was turned on.

Random numbers are quite important in applied computing. For example, 
video games generate and use many random numbers per second to keep
events and the behavior of non-player characters from being too 
predictable.

## Using a uniform random number to generate a number from another distribution

There is a simple result in the mathematics of probability.
Suppose that x is a random number drawn from the standard uniform
distribution, and we want a random number drawn from some
other distribtuion.  Let F() be the CDF of our desired distribution,
and let y=F-1(x).  Then y has our desired distribution.

Now that's very mathy, but it's easy to put in practice.


# Some applications

## Making a craps game in Excel

We can use Excel to simulate the casino game craps. In craps, 
a player (the "shooter") repeatedly rolls a pair of six-sided 
dice, and players can bet on what the shooter rolls.  There 
are many different bets you can make, but we will focus on the
one called the "pass line" bet. The shooter
is required to place this particular bet, and it is by far the
most common bet for the other players. Players take turns being 
shooter.

Here are the rules:

- The shooter's first roll is called the "come out" roll.
  - If the come out roll is a 7 or 11, the shooter wins.
  - If the come out roll is a 2,3, or 12, the shooter loses.
  - If the come out roll is any other number, the game continues and 
    that number is called the "point" for the rest of the game.
- Once a point is established, the shooter continues rolling until either
  - The shooter rolls the point again, and wins.
  - The shooter rolls a 7, and loses.

Let's simulate a craps game in Excel.  The first step is to simulate the rolls.
We actually don't know in advance how many rolls there will be, but let's just
simulate 100 rolls and throw away any rolls that occur after the game has
ended.

1. Use RANDBETWEEN() to generate a random number in cell A1 representing the 
   roll of a single 6-sided die.  
2. Copy cell A1 to cells A1:B100.  Each row now represents the roll of a
   pair of six-sided dice.
3. The bets in craps are based on the total showing on the two dice, so fill 
   in cells C1:C100 with that total.

The next step is to map the rolls into outcomes.

1. We start by producing outcomes for the come-out roll. 
   a. Use the IFS() function to 
      make cell E1 contain the following:
      - "WIN" if the come-out roll wins
      - "LOSE" if the come-out roll loses
      - "POINT=" if the come-out roll establishes a point.
   b. Use the IF() or IFS() function to make cell E2 contain:
      - The point, if the come-out roll establishes a point.
      - Nothing ("") if the come-out roll establishes a point.
3. Now we produce outcomes for the other rolls.
   a. Use the IFS() function to make cell E2 contain the following
      - "WIN" if the shooter wins on this roll.
      - "LOSE" if the shooter loses on this roll.
      - "." if the game continues after this roll.
      - "" if the game has ended.
   b. Copy cell E2 to cells E2:E100 to make each cell contain
      the result of that roll.  Please note that you may 
      have to make some references in cell E2 absolute
      in order for the cell to copy correctly.
      
At this point we should have a full-fledged craps game.
To "play" the game, hit the F9 key to generate a new set 
of random numbers, and look at the outcome.

ASSIGNMENT: Play the game 10 times, and count how many
wins and losses you have. Give me that number.




